on: push
name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@master
        with:
          image-reference: "localbuild/testimage:latest"
          dockerfile-path: "Dockerfile"
          fail-build: true
          debug: true
